[workspace]
members = [ "bins/cargo-hybrid", "bins/node", "crates/compile", "crates/vm", "crates/hybrid_evm"]


exclude = ["contracts/*", "examples/*"]

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0.98"
indicatif = "0.17"
colored = "2.1"
eyre = "0.6"

# reth 
# reth = { git = "https://github.com/developeruche/reth.git", rev = "54ed1ac9dc087b909e346ba2855935edee7c5764" }
# reth-ethereum = { git = "https://github.com/developeruche/reth.git", rev = "54ed1ac9dc087b909e346ba2855935edee7c5764" }
# reth-tracing = { git = "https://github.com/developeruche/reth.git", rev = "54ed1ac9dc087b909e346ba2855935edee7c5764" }
# reth-ethereum-payload-builder = { git = "https://github.com/developeruche/reth.git", rev = "54ed1ac9dc087b909e346ba2855935edee7c5764" }

reth = { path = "../../CONTRIBUTIONS/reth/bin/reth" }
reth-ethereum = { path = "../../CONTRIBUTIONS/reth/crates/ethereum/reth" }
reth-tracing = { path = "../../CONTRIBUTIONS/reth/crates/tracing" }
reth-ethereum-payload-builder = { path = "../../CONTRIBUTIONS/reth/crates/ethereum/payload" }

alloy-evm = { version = "0.5.0", default-features = false }
alloy-genesis = { version = "0.14.0", default-features = false }
alloy-primitives = { version = "1.0.0", default-features = false, features = ["map-foldhash"] }


# revm
revm = { version = "22.0.1", default-features = false }