[workspace]
members = [ "bins/cargo-hybrid", "bins/node", "crates/compile", "crates/vm", "crates/hybrid_evm"]


exclude = ["contracts/*", "examples/*"]

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0.98"
indicatif = "0.17"
colored = "2.1"
eyre = "0.6"

# reth 
reth = { git = "https://github.com/paradigmxyz/reth.git", branch = "main"}
reth-ethereum = { git = "https://github.com/paradigmxyz/reth.git", branch = "main"}
reth-tracing = { git = "https://github.com/paradigmxyz/reth.git", branch = "main"}
alloy-evm = { git = "https://github.com/developeruche/alloy-evm.git", rev = "70143f5c2916bdc217dd55b575ea231c5fda5a39", default-features = false }
# alloy-evm = { git = "https://github.com/developeruche/alloy-evm.git", branch = "hybrid-evm", default-features = false }
alloy-genesis = { version = "1.0.1", default-features = false }
alloy-primitives = { version = "1.1.0", default-features = false, features = ["map-foldhash"] }


# revm
revm = { version = "23.1.0", default-features = false }