[workspace]
members = [ "bins/cargo-hybrid", "bins/dev-node","bins/node", "crates/compile", "crates/vm"]


exclude = ["contracts/*", "examples/*"]

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0.98"


