[workspace]
members = [ "bins/cargo-hybrid", "bins/node", "crates/compile", "crates/vm"]


exclude = ["contracts/*", "examples/*", "crates/hybrid_evm"]

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0.98"
indicatif = "0.17"
colored = "2.1"
eyre = "0.6"

# reth 
reth = { git = "https://github.com/paradigmxyz/reth.git", rev = "6f8e7258f4733279080e4bd8345ce50538a40d6e" }
reth-ethereum = { git = "https://github.com/paradigmxyz/reth.git", rev = "6f8e7258f4733279080e4bd8345ce50538a40d6e" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth.git", rev = "6f8e7258f4733279080e4bd8345ce50538a40d6e" }

alloy-evm = { version = "0.5.0", default-features = false }
alloy-genesis = { version = "0.14.0", default-features = false }
alloy-primitives = { version = "1.0.0", default-features = false, features = ["map-foldhash"] }


# revm
revm = { version = "23.1.0", default-features = false }