[package]
name = "mini-evm-interpreter"
version.workspace = true
license.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
revm.workspace = true
hybrid-vm.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
bincode.workspace = true